### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by bfishman** [mappum/electron-webrtc#15]
Hello. I'm getting an unhandled error which results in a crash:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at Pipe.onread (net.js:544:26)
```

This seems to happen when the electron-webrtc  has run once, been shut down, then run again.

I do handle the error events as directed:
```
// call exported function to create Electron process 
var wrtc = require('electron-webrtc')();

// handle errors that may occur when trying to communicate with Electron 
wrtc.on('error', function (err) { logger.warn("WRTC error: " + err) });
```

Am I missing something?

**Comment by mappum** [comment]
How can I reproduce this?

>This seems to happen when the electron-webrtc has run once, been shut down, then run again.

Do you mean something like this?:
```js
var electronWebrtc = var wrtc = require('electron-webrtc')
var wrtc = electronWebrtc()
wrtc.close()
wrtc = electronWebrtc()
```

**Comment by bfishman** [comment]
No, sorry. I mean when a node server, which calls `var electronWebrtc = var wrtc = require('electron-webrtc')` is launched, closed, then relaunched.

My real concern is the Unhandled 'error' - I'm handling `wrtc.on('error'...)`, so I wonder if an error is bubbling up from deeper in the library and not being caught along the way?

**Comment by mappum** [comment]
Your error is coming from a TCP connection, and `electron-webrtc` does not create any connections (it does inter-process communication using the spawned process's stdio). Could this error be coming from elsewhere in your program?

**Comment by bfishman** [comment]
I am using socket io, perhaps that's it. But using other webRTC libraries (node-webrtc, webrtc-native) this does not occur.

**Comment by mappum** [comment]
@bfishman did you ever figure out anything about this error?

**Comment by bfishman** [comment]
Not yet, haven't done any further troubleshooting. Will have a little time tonight to try again however.

**Comment by bfishman** [comment]
Sorry, didn't get to it. Been traveling the past two weeks. I'm going to try adding in some generic error handling, hopefully it's a node issue and not related to the RTC code. Just weird that it happens here but not when using node-webrtc or webrtc-native. Will report back I've done some further troubleshooting.

**Comment by mappum** [comment]
No worries! Let me know if you need any help figuring it out.

**Comment by bfishman** [comment]
Over the course of troubleshooting, I realized that if I do not use Xvfb to create a display, the electron-webrtc module works perfectly (aside from creating a blank display rectangle on my screen). 

If I do use Xvfb as described in this repo's Readme.md, I can get past the unhandled error message by removing the following from my code:

```
io = socketIO;
io.on('error', function(error){
    logger.error(error.name + ': ' + error.message);
});
```

But something else is going on, because RTCPeerConnection.createOffer() never seems to execute (either promise API or deprecated callback API).

Any advice on how to properly use Xvfb?  Ubuntu 15.10, Node 4.3.

**Comment by mappum** [comment]
@bfishman Thanks for the update on this issue. The problem is showing up here as well: https://github.com/feross/bittorrent-tracker/pull/139#event-604270674

I wasn't aware of the xvfb node module, thanks for the heads up. Maybe it would be a good idea to put that in `electron-eval` with an option to enable it (or autodetect when it should be used).

**Comment by bfishman** [comment]
Everything is working great now, by the way. This is probably a chromium implementation "bug", but when you try to create a second datachannel prior to a first one being opened, both returned variables refer to the same datachannel and only one is created. One must wait until the first is fully created before trying to create a second. Again, though, likely a chromium implementation quirk. Anyway, great work with this repo!

For posterity / others viewing this issue, here's how I use the xvfb module:

```
var Xvfb = require('xvfb');

var xvfb = new Xvfb(99, true);
xvfb.startSync();

// call exported function to create Electron process 
var wrtc = require('electron-webrtc')();

// handle errors that may occur when trying to communicate with Electron 
wrtc.on('error', function (err) { logger.warn("WRTC error: " + err) });
```

**Comment by mappum** [comment]
Hm, sounds more like a bug in this module, not Chromium. I'll try debugging it.

**Comment by mappum** [comment]
Thanks for the Xvfb example :)

**Comment by mappum** [comment]
This should be resolved now that `electron-eval` has an option to start Xvfb via `node-xvfb`.

**Comment by bfishman** [comment]
@mappum For some reason the NPM version of electron-webrtc is still referencing electron-eval v0.3.1. The current git repo, however, correctly references v0.5.0. Point is, a naive `npm install --save electron-webrtc` does not work as expected. I had to clone this repo inside of my project's node_modules folder, then npm install from node_modules/electron-webrtc.

**Comment by mappum** [comment]
Oops, never published it. Thanks for the heads up. :)

**Comment by Simon-L** [comment]
I think I am still having this issue. I'm working on a relatively big project that was also using websockets to do signaling. I made an extremely stripped down version of the code to test, `package.json` is as follows:
```json
{
  "name": "test-headless-electron-webrtc",
  "version": "1.0.0",
  "description": "test headless electron-webrtc",
  "main": "index.js",
  "dependencies": {
    "electron-webrtc": ""
  }
}
```

`index.js` is similarly limited:
```js
var wrtc = require('electron-webrtc')({headless: true})

wrtc.on('error', function (err) {
  console.log("This is a wrtc error!")
  console.log(err)
})
```
As previously stated, the first I run `nodejs index.js` it just hangs infinitely, I'm assuming this is the right behaviour.
If I close it with `Ctrl+C` (no message appears when quitting) and rerun the same `nodejs index.js` this is what I get:
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:870:11)
    at WriteWrap.afterWrite (net.js:769:14)
```
This is on Ubuntu Server 15.04, xvfb is correctly installed, `npm install` went without issue.

I should note that this works on my Linuxmint 17.2 laptop, I can stop and rerun the process as I wish. Interestingly, stdout is giving some output that I do not get when running headless, it's about the initialisation of a few dozen extension to X(vfb).

Should I be giving electron-webrtc more opts regarding xvfb?
I am suspecting this also has to do with some packages related to Xorg. It might be using local sockets to exchange between running softwares, hence the reference to net.js and EPIPE error in nodejs.

Thanks a lot for helping! I have been focusing exclusively on this issue for three/four days already.

**Comment by mappum** [comment]
@Simon-L Thanks for making it easy to reproduce, I'll test it out a few hours from now when I get to a computer.

I noticed you use the `nodejs` binary rather than `node`, which implies you installed it via `apt-get`. Which version of node are you on? (I think the apt package is usually pretty far out of date).

Thanks for your patience and diligence, let's get this bug ironed out once and for all!

**Comment by Simon-L** [comment]
I am using Node 4.x from nodesource, following the instructions from here: https://github.com/nodesource/distributions#debinstall
If there is an easier and more preferred way of installing a recent nodejs version I'd be happy to change my habits!
I indeed used apt-get only to get a more up to date version!
Seems I am on v4.4.2 on all laptops and servers I've tested.

Another test: I started my Linuxmint laptop in text mode (root recovery mode from Grub) so that no X is started and the test code above worked, this points me in the direction of looking at installed packages. Maybe missing packages... I want to try installing a minimal X without actually running it, just enough to see if it makes it work.

**Comment by Simon-L** [comment]
It runs "better"(tm) after installing xorg (`apt-get install xorg`).
But then the behaviour looks very erratic, I can get it to work, sometimes... After adding some more logging it seems to work, sometimes... I really can't find a pattern in this.
One thing though, it looks like it's more on `electron-eval` or even `node-xvfb` side that it's broken.
